#!/bin/csh
#SBATCH -p par6.q
#SBATCH -N 64
#SBATCH --ntasks-per-node=1
#SBATCH -t 08:00:00
#SBATCH --exclusive

module purge
module load intel/xe_2015.2
module load intelmpi/intel/5.0.3
module load must/impi/intel/1.4.0
module load slurm
module load sge

mpirun ./tribal
